
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Sprawdź czy klucze są dostępne
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("Brak konfiguracji SUPABASE_URL lub SUPABASE_ANON_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);

// Dla debugowania
console.log("Inicjalizacja Supabase klienta");
console.log("Supabase URL configured:", SUPABASE_URL ? "YES" : "NO");
console.log("Supabase ANON KEY configured:", SUPABASE_ANON_KEY ? "YES" : "NO");
